export interface IAlbum {
  id: string;
  name: string;
}

// Generated by https://quicktype.io

export interface IAlbumResponse {
  album_type:             string;
  total_tracks:           number;
  available_markets:      string[];
  external_urls:          ExternalUrls;
  href:                   string;
  id:                     string;
  images:                 Image[];
  name:                   string;
  release_date:           string;
  release_date_precision: string;
  restrictions:           Restrictions;
  type:                   string;
  uri:                    string;
  artists:                Artist[];
  tracks:                 Tracks;
}

export interface Artist {
  external_urls: ExternalUrls;
  followers:     Followers;
  genres:        string[];
  href:          string;
  id:            string;
  images:        Image[];
  name:          string;
  popularity:    number;
  type:          string;
  uri:           string;
}

export interface ExternalUrls {
  spotify: string;
}

export interface Followers {
  href:  string;
  total: number;
}

export interface Image {
  url:    string;
  height: number;
  width:  number;
}

export interface Restrictions {
  reason: string;
}

export interface Tracks {
  href:     string;
  items:    Item[];
  limit:    number;
  next:     string;
  offset:   number;
  previous: string;
  total:    number;
}

export interface Item {
}
